### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by XeonG** [Schwapo/Odin-Resolved-Parameters-Overview#1]
NullReferenceException: Object reference not set to an instance of an object
Schwapo.OdinInspector.Editor.ResolvedParametersOverviewWindow.ResolvedParametersOverviewWindow.SearchedFor (System.String str) (at Assets/Modded Tools/ResolvedParametersOverviewWindow/Editor/ResolvedParametersOverviewWindow.cs:85)
Schwapo.OdinInspector.Editor.ResolvedParametersOverviewWindow.AttributeWithResolvedParametersDrawer+<>c.<DrawPropertyLayout>b__12_0 (Schwapo.OdinInspector.Editor.ResolvedParametersOverviewWindow.ResolvedParameter p) (at Assets/Modded Tools/ResolvedParametersOverviewWindow/Editor/AttributeWithResolvedParametersDrawer.cs:84)
System.Linq.Enumerable+WhereListIterator`1[TSource].MoveNext () (at <7c74ff6d21b945ec8c6d643fc331621b>:0)
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <7c74ff6d21b945ec8c6d643fc331621b>:0)
Schwapo.OdinInspector.Editor.ResolvedParametersOverviewWindow.AttributeWithResolvedParametersDrawer.DrawPropertyLayout (UnityEngine.GUIContent label) (at Assets/Modded Tools/ResolvedParametersOverviewWindow/Editor/AttributeWithResolvedParametersDrawer.cs:90)
Sirenix.OdinInspector.Editor.OdinDrawer.CallNextDrawer (UnityEngine.GUIContent label) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155)
Sirenix.OdinInspector.Editor.Drawers.FixUnityNullDrawer`1[T].DrawPropertyLayout (UnityEngine.GUIContent label) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/FixUnityNullDrawer.cs:87)
Sirenix.OdinInspector.Editor.OdinDrawer.CallNextDrawer (UnityEngine.GUIContent label) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:155)
Sirenix.OdinInspector.Editor.Drawers.ReferenceDrawer`1[T].DrawPropertyLayout (UnityEngine.GUIContent label) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/Misc Drawers/ReferenceDrawer.cs:118)
Sirenix.OdinInspector.Editor.OdinDrawer.DrawProperty (UnityEngine.GUIContent label) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Drawers/OdinDrawer.cs:109)
Sirenix.OdinInspector.Editor.InspectorProperty.Draw (UnityEngine.GUIContent defaultLabel) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:849)
Rethrow as OdinPropertyException: This error occurred while being drawn by Odin.
Current IMGUI event: Layout
Odin Property Path: $ROOT
Odin Drawer Chain:
> ReferenceDrawer<AttributeWithResolvedParameters>
> FixUnityNullDrawer<AttributeWithResolvedParameters>
> ValidationDrawer<AttributeWithResolvedParameters>
> AttributeWithResolvedParametersDrawer
> CompositeDrawer.
UnityEngine.Debug:LogException(Exception)
Sirenix.OdinInspector.Editor.InspectorProperty:Draw(GUIContent) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/InspectorProperty.cs:926)
Sirenix.OdinInspector.Editor.PropertyTree:DrawProperties() (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/PropertyTree.cs:556)
Sirenix.OdinInspector.Editor.PropertyTree:Draw(Boolean) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/Core/PropertyTree.cs:448)
Sirenix.OdinInspector.Editor.OdinEditorWindow:DrawEditor(Int32) (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/OdinEditorWindow/OdinEditorWindow.cs:997)
Sirenix.OdinInspector.Editor.OdinEditorWindow:DrawEditors() (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/OdinEditorWindow/OdinEditorWindow.cs:803)
Sirenix.OdinInspector.Editor.OdinEditorWindow:OnGUI() (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/OdinEditorWindow/OdinEditorWindow.cs:748)
Sirenix.OdinInspector.Editor.OdinMenuEditorWindow:OnGUI() (at C:/Sirenix/Sirenix Solution/Sirenix.OdinInspector.Editor/OdinEditorWindow/OdinMenuEditorWindow.cs:340)
Schwapo.OdinInspector.Editor.ResolvedParametersOverviewWindow.ResolvedParametersOverviewWindow:OnGUI() (at Assets/Modded Tools/ResolvedParametersOverviewWindow/Editor/ResolvedParametersOverviewWindow.cs:45)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

GUI Error: Invalid GUILayout state in ResolvedParametersOverviewWindow view. Verify that all layout Begin/End calls match
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by schwapo** [comment]
It should work now 👍🏼
